/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aep;

/**
 *
 * @author Mateus
 */
public class HomeFuncionario extends javax.swing.JFrame {

    /**
     * Creates new form HomeFuncionario
     */
    public HomeFuncionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HomePainel = new javax.swing.JPanel();
        homeMenuBar = new javax.swing.JMenuBar();
        ItemMenuUsuarios = new javax.swing.JMenu();
        subItemCadastrarUsuario = new javax.swing.JMenuItem();
        subItemAlterarUsuarios = new javax.swing.JMenuItem();
        subItemDesativarUsuarios = new javax.swing.JMenuItem();
        itemMenuFormularios = new javax.swing.JMenu();
        subItemFormulario = new javax.swing.JMenu();
        subItemFormularioCriar = new javax.swing.JMenuItem();
        subItemFormularioDesativar = new javax.swing.JMenuItem();
        subItemFormularioAlterar = new javax.swing.JMenuItem();
        subItemPergunta = new javax.swing.JMenu();
        subItemPerguntaCriar = new javax.swing.JMenuItem();
        subItemPerguntaDesativar = new javax.swing.JMenuItem();
        subItemPerguntaAlterar = new javax.swing.JMenuItem();
        subItemResposta = new javax.swing.JMenu();
        subItemRespotaCriar = new javax.swing.JMenuItem();
        subItemRespostaDesativar = new javax.swing.JMenuItem();
        subItemRespostaAlterar = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        itemMenuEstatistica = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        HomePainel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout HomePainelLayout = new javax.swing.GroupLayout(HomePainel);
        HomePainel.setLayout(HomePainelLayout);
        HomePainelLayout.setHorizontalGroup(
            HomePainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 481, Short.MAX_VALUE)
        );
        HomePainelLayout.setVerticalGroup(
            HomePainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );

        homeMenuBar.setBackground(new java.awt.Color(255, 0, 66));
        homeMenuBar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        homeMenuBar.setForeground(new java.awt.Color(255, 0, 66));
        homeMenuBar.setOpaque(false);

        ItemMenuUsuarios.setBackground(new java.awt.Color(255, 0, 66));
        ItemMenuUsuarios.setBorder(null);
        ItemMenuUsuarios.setForeground(new java.awt.Color(255, 0, 66));
        ItemMenuUsuarios.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 12)); // NOI18N
        ItemMenuUsuarios.setLabel("USUÁRIOS");

        subItemCadastrarUsuario.setForeground(new java.awt.Color(255, 0, 66));
        subItemCadastrarUsuario.setText("Cadastrar");
        subItemCadastrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subItemCadastrarUsuarioActionPerformed(evt);
            }
        });
        ItemMenuUsuarios.add(subItemCadastrarUsuario);

        subItemAlterarUsuarios.setForeground(new java.awt.Color(255, 0, 66));
        subItemAlterarUsuarios.setText("Alterar");
        subItemAlterarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subItemAlterarUsuariosActionPerformed(evt);
            }
        });
        ItemMenuUsuarios.add(subItemAlterarUsuarios);

        subItemDesativarUsuarios.setForeground(new java.awt.Color(255, 0, 66));
        subItemDesativarUsuarios.setText("Desativar");
        ItemMenuUsuarios.add(subItemDesativarUsuarios);

        homeMenuBar.add(ItemMenuUsuarios);

        itemMenuFormularios.setBorder(null);
        itemMenuFormularios.setForeground(new java.awt.Color(255, 0, 66));
        itemMenuFormularios.setText("FORMULÁRIOS");
        itemMenuFormularios.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 12)); // NOI18N

        subItemFormulario.setForeground(new java.awt.Color(255, 0, 66));
        subItemFormulario.setText("Formulário");

        subItemFormularioCriar.setForeground(new java.awt.Color(255, 0, 66));
        subItemFormularioCriar.setText("Criar");
        subItemFormulario.add(subItemFormularioCriar);

        subItemFormularioDesativar.setForeground(new java.awt.Color(255, 0, 66));
        subItemFormularioDesativar.setText("Desativar");
        subItemFormulario.add(subItemFormularioDesativar);

        subItemFormularioAlterar.setForeground(new java.awt.Color(255, 0, 66));
        subItemFormularioAlterar.setText("Alterar");
        subItemFormulario.add(subItemFormularioAlterar);

        itemMenuFormularios.add(subItemFormulario);

        subItemPergunta.setForeground(new java.awt.Color(255, 0, 66));
        subItemPergunta.setText("Pergunta");

        subItemPerguntaCriar.setForeground(new java.awt.Color(255, 0, 66));
        subItemPerguntaCriar.setText("Criar");
        subItemPergunta.add(subItemPerguntaCriar);

        subItemPerguntaDesativar.setForeground(new java.awt.Color(255, 0, 66));
        subItemPerguntaDesativar.setText("Desativar");
        subItemPergunta.add(subItemPerguntaDesativar);

        subItemPerguntaAlterar.setForeground(new java.awt.Color(255, 0, 66));
        subItemPerguntaAlterar.setText("Alterar");
        subItemPergunta.add(subItemPerguntaAlterar);

        itemMenuFormularios.add(subItemPergunta);

        subItemResposta.setForeground(new java.awt.Color(255, 0, 66));
        subItemResposta.setText("Resposta");

        subItemRespotaCriar.setForeground(new java.awt.Color(255, 0, 66));
        subItemRespotaCriar.setText("Criar");
        subItemResposta.add(subItemRespotaCriar);

        subItemRespostaDesativar.setForeground(new java.awt.Color(255, 0, 66));
        subItemRespostaDesativar.setText("Desativar");
        subItemResposta.add(subItemRespostaDesativar);

        subItemRespostaAlterar.setForeground(new java.awt.Color(255, 0, 66));
        subItemRespostaAlterar.setText("Alterar");
        subItemResposta.add(subItemRespostaAlterar);

        itemMenuFormularios.add(subItemResposta);

        homeMenuBar.add(itemMenuFormularios);
        homeMenuBar.add(jMenu1);

        itemMenuEstatistica.setBackground(new java.awt.Color(255, 255, 255));
        itemMenuEstatistica.setBorder(null);
        itemMenuEstatistica.setForeground(new java.awt.Color(255, 0, 66));
        itemMenuEstatistica.setText("ESTATÍSTICAS");
        itemMenuEstatistica.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 12)); // NOI18N
        homeMenuBar.add(itemMenuEstatistica);

        setJMenuBar(homeMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HomePainel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HomePainel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void subItemAlterarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subItemAlterarUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subItemAlterarUsuariosActionPerformed

    private void subItemCadastrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subItemCadastrarUsuarioActionPerformed
        
    }//GEN-LAST:event_subItemCadastrarUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel HomePainel;
    private javax.swing.JMenu ItemMenuUsuarios;
    private javax.swing.JMenuBar homeMenuBar;
    private javax.swing.JMenu itemMenuEstatistica;
    private javax.swing.JMenu itemMenuFormularios;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem subItemAlterarUsuarios;
    private javax.swing.JMenuItem subItemCadastrarUsuario;
    private javax.swing.JMenuItem subItemDesativarUsuarios;
    private javax.swing.JMenu subItemFormulario;
    private javax.swing.JMenuItem subItemFormularioAlterar;
    private javax.swing.JMenuItem subItemFormularioCriar;
    private javax.swing.JMenuItem subItemFormularioDesativar;
    private javax.swing.JMenu subItemPergunta;
    private javax.swing.JMenuItem subItemPerguntaAlterar;
    private javax.swing.JMenuItem subItemPerguntaCriar;
    private javax.swing.JMenuItem subItemPerguntaDesativar;
    private javax.swing.JMenu subItemResposta;
    private javax.swing.JMenuItem subItemRespostaAlterar;
    private javax.swing.JMenuItem subItemRespostaDesativar;
    private javax.swing.JMenuItem subItemRespotaCriar;
    // End of variables declaration//GEN-END:variables
}
